/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$addBook_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<head>\n  <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n</head>\n<form action=\"addData\" method=\"post\" id=\"myForm\">\n  Book Id\n  <br/>\n  <input type=\"text\" name=\"BookId\"/>\n  <br/>\n  Book Name\n  <br/>\n  <input type=\"text\" name=\"BookName\"/>\n  <br/>\n  Book Author\n  <br/>\n  <input type=\"text\" name=\"BookAuthor\"/>\n  <br/>\n  <input type=\"button\" id=\"iAmGoodBtn\" class=\"iAmGoodBtn\" value=\"add\"/>\n  <!-- /| validate = function() {var x = document.forms[\"myForm\"][\"BookId\"].value;if (x == null || x == \"\") {alert(\"enter some data\"); return false;}} -->\n</form>\n" );
    }
  }
}


class $_scalate_$addBook_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$addBook_jade.$_scalate_$render(context)
}
