/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$main_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<h1>The BookStore</h1>\n<form action=\"addBook\" method=\"get\">\n  <button id=\"addbutton\" value=\"button\" onclick=\"return validate()\">\n    <h3>Add</h3>\n  </button>\n</form>\n<form action=\"searchBook\" method=\"get\">\n  <button id=\"addbutton\" value=\"button\" onclick=\"return validate()\">\n    <h3>Search</h3>\n  </button>\n</form>\n<!-- /form(action='deleteBook' method='get') -->\n<!-- /\tbutton(id=\"addbutton\" value=\"button\" onclick=\"return validate()\") -->\n<!-- /\t\th3 Delete -->\n<!-- /form(action='updateBook' method='get') -->\n<!-- /\tbutton(id=\"addbutton\" value=\"button\" onclick=\"return validate()\") -->\n<!-- /\t\th3 Update -->\n" );
    }
  }
}


class $_scalate_$main_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$main_jade.$_scalate_$render(context)
}
